### ISSUE TITLE
Type safe `combineLatest`?

### ISSUE THREAD

**Issue by brianegan** [frankpepermans/rxdart#10]
Hey there, thanks so much for the Rx port to Dart! One question: I was using this lib + combineLatest in Strong Mode, but `combineLatest` simply takes an `Iterable<Stream<dynamic>>`, and a `Function` as the predicate, therefore losing all type information about the values within the predicate. 

Now that we have proper method generics type inference in dart 1.21+, would you be open to a PR that makes this more Type Safe?

RxJava does this in the following way:
https://github.com/ReactiveX/RxJava/blob/010256b0e19bdb18f136f80a4dc48c0a53c3da41/src/main/java/rx/Observable.java#L686

Pseudo-proposal:

```
typedef R CombineTwoPredicate<T1, T2, R>(T1 t1, T2 t2);
typedef R CombineThreePredicate<T1, T2, T3, R>(T1 t1, T2 t2, T3 t3);

Observable.combineLatest(S1 s1, S2 s2, CombineTwoPredicate predicate)
Observable.combineThreeLatest(S1 s1, S2 s2, S3 s3, CombineThreePredicate predicate)
```

Again, thanks for your effort, and happy to help contribute! Lemme know whatcha think :)

**Comment by frankpepermans** [comment]
I might be wrong about this, but I don't think there's currently a way to specify the generic stream types as described in your example.

Observable only knows type T, the event type (in this case where T is the generic type returned by the predicate).

So the following snipped will be accepted by the analyzer:
`factory Observable.combineTwoLatest(
      Stream streamA, Stream streamB, T predicate(dynamic eventFromA, dynamic eventFromB)) => ...`

However, trying to add types for the Streams would not work, i.e.
`factory Observable.combineTwoLatest(
      Stream<R> streamA, Stream<S> streamB, T predicate(R eventFromA, S eventFromB)) => ...`

Using a `typedef` would not solve the problem either...

So yes, a type check on the predicate would be possible (and still very handy),
but alas there's no way to describe a dynamic amount of arguments in Dart like `T predicate(args...)` so pulling apart combineLatest (and zip, ...) into combineTwoLatest, combineThreeLatest, etc... would still be required, each with their own x-length predicate that returns type T.

**Comment by brianegan** [comment]
`into combineTwoLatest, combineThreeLatest, etc... would still be required, each with their own x-length predicate that returns type T.`

Yep, totally. This is exactly what RxJava does, and exactly my proposal to get type safety in the predicates. 

RxJava declares 8 versions of the `combineLatest` method that takes from 2-9 arguments so they can capture the Type of the stream, and have a corresponding "typedef" to keep the type info for each predicate. Unfortunately, it's a pain in dart as Dart doesn't allow method overloading, so we'd need not only 8 predicate typedefs but also 8 different method names :(

Now, if you needed to combine more than 9 items you'd be out of luck. That said, in 2 years of using Rx in production apps, I haven't quite seen that need myself, so figured RxJava might be on to something.

That's why I wanted to see what your thoughts were before submitting a PR! It's a bit goofy in Dart b/c of lack of Method overloading, but might still be handy?

Not sure the best approach here... thanks for taking the time to think and comment about it!

**Comment by frankpepermans** [comment]
See the latest commit (example: https://github.com/frankpepermans/rxdart/blob/master/test/observable/combine_latest_test.dart#L51)

Unfortunately, if we want type support on the Streams we pass, a factory constructor won't work (factory can only work with generic class types, not generic method types).

So instead, static methods have been added on Observable.

`Observable<String> obs = Observable.combineTwoLatest(
    new Stream.fromIterable([1, 2, 3, 4]),
    new Stream.fromIterable([5, 6, 7, 8]),
    (int a, int b) => '$a:$b'
);`

The predicate enforces types, so `int A` and `int B` will force both Streams to be of event type int as well.
The return type is Observable<String> as implied from the predicate as well.

The same has been done for `zip`.

**Comment by brianegan** [comment]
Two for two! Thanks again, so cool to see this library getting better and better :)
