### ISSUE TITLE
startWith that takes a single value?

### ISSUE THREAD

**Issue by brianegan** [frankpepermans/rxdart#11]
Another proposal, happy to help! I find when using this library + startWith, I'm always passing in a single value rather than a list. Therefore, I always have to wrap this initial value in brackets. Not a biggie, but seems like this method might cater for the 20% rather than the 80%. 

Would you be open to having two methods for `startWith` (since Dart doesn't support overloading)?

What I'm thinking:

```
startWith(A value)
startWithIterable(Iterable<A> values)
```

Thanks again for the lib!

**Comment by frankpepermans** [comment]
I have the same problem ;)

Would suggest to keep startWith as-is, and add startWithSingle instead, so nothing breaks when upgrading rxdart?

**Comment by brianegan** [comment]
Ah, interesting reversal! Personally, since I looked at RxDart as a 0.5 version, I assumed the API was open to breaking changes as it hasn't hit 1.0 yet. 

Given that we've both found `startWith` makes more sense as a single value by default, I'd argue that optimizing for the most common use case is the better approach, and play your "not 1.0" card to make a breaking change.

What are your thoughts?

**Comment by frankpepermans** [comment]
I've no idea as to how many people are using rxdart at the moment :/ 

So startWith and startWithMany then?

Might make more sense, given the other issue where you'd get combineLatest vs combineXLatest as single vs many.

(Or zip and zipThree, zipX etc...)

**Comment by frankpepermans** [comment]
Went ahead with implementing startWith and startWithMany in v0.6.0

**Comment by brianegan** [comment]
Yay! Thanks for taking my feedback into consideration :)
