### ISSUE TITLE
rxdart 0.5.0 appears to be missing from pub?

### ISSUE THREAD

**Issue by dustinlessard-wf** [frankpepermans/rxdart#5]
A few days ago, I was able to pull this version from pub but now I cannot.  0.4.8 is the latest I can successfully get.

**Comment by zoechi** [comment]
What does that mean? 0.5.0 is there https://pub.dartlang.org/packages/rxdart (Versions tab).
Perhaps you have another dependency that is not compatible with 0.5.0.
Do you get any error message?

**Comment by frankpepermans** [comment]
0.5.0 Has an updated dependency on SDK 1.21.0
(hence the bump from 0.4.x to 0.5.0)

SDK 1.21.0 supports generic method syntax finally, so the old 'commented style' is removed in this version.

Maybe this is causing rxdart not to upgrade to 0.5.0 for you?

**Comment by dustinlessard-wf** [comment]
(facepalm)
Sorry gents, I didn't realize I was on an old version of the SDK.  False alarm - will close this issue.
