### ISSUE TITLE
Question : How does one see the test coverage for this code?

### ISSUE THREAD

**Issue by dustinlessard-wf** [frankpepermans/rxdart#9]

**Comment by frankpepermans** [comment]
See the coveralls line in the [.travis.yml](https://github.com/frankpepermans/rxdart/blob/master/.travis.yml#L16) build file

**Comment by dustinlessard-wf** [comment]
Ok ty!

**Comment by frankpepermans** [comment]
Turns out dart_coveralls is broken as of Dart SDK 1.16.0 :(

The actual code coverage percentage is somewhere in the 90ies, I'll see if I can fix the Travis reporting...

**Comment by frankpepermans** [comment]
See the updated travis file, we now point to codecov.io which renders a very nice report of the coverage!
